title: Dongxun Jiang's Homepage
page-top-title: Dongxun Jiang
top-section-bg-text: Be what you wanna be
home-subtitle: Dongxun Jiang&ensp;|&ensp;蒋东珣
copyright-text: '&copy; Dongxun Jiang 2023-2025. All Rights Reserved.'
